spring.application.name=spending-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:spending_manager}
spring.datasource.username=${DB_USER:spending_manager}
spring.datasource.password=${DB_PASSWORD:spending}
spring.jpa.hibernate.ddl-auto=validate
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB