spring.application.name = spending-manager

spring.datasource.url = jdbc:postgresql://localhost:5432/${DB_NAME:spending_manager}
spring.datasource.username = ${DB_USER:spending_manager}
spring.datasource.password = ${DB_PASSWORD:spending}

management.endpoint.health.show-details = always